import { useEffect, useMemo, useRef, useState } from "react";
import { LanguageProvider, useLanguage, type Language } from "./i18n";
import {
  applyRetentionResult,
  completed,
  completion,
  eligibleRecallTerms,
  makeCloze,
  makeLetterBank,
  makeTerm,
  migrateLegacyExamples,
  normalizeAnswer,
  retentionPercentage,
  safeSets,
  selectRecallTerms,
  seed,
  stageFor,
  uid,
  type StudySet,
  type Term,
  type RecallTerm,
  type RetentionResult,
  type View,
} from "./study";

export default function Home(){
  const [language,setLanguage]=useState<Language>(()=>localStorage.getItem("pocket-flashcards-language")==="mi"?"mi":"en");
  useEffect(()=>{localStorage.setItem("pocket-flashcards-language",language);document.documentElement.lang=language==="mi"?"mi":"en"},[language]);
  return <LanguageProvider language={language}><PocketFlashcards language={language} setLanguage={setLanguage}/></LanguageProvider>
}

function PocketFlashcards({language,setLanguage}:{language:Language;setLanguage:(language:Language)=>void}){
  const {tr}=useLanguage();
  const [sets,setSets]=useState<StudySet[]>([]); const [ready,setReady]=useState(false); const [view,setView]=useState<View>({kind:"library"});
  const [modal,setModal]=useState<null|"new"|"rename"|"delete"|"term"|"reset-review"|"reset-term">(null); const [draft,setDraft]=useState(""); const [desc,setDesc]=useState(""); const [editId,setEditId]=useState<string|null>(null); const [notice,setNotice]=useState("");
  const fileRef=useRef<HTMLInputElement>(null);
  // Browser storage is intentionally restored after the first client render.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{try{const saved=localStorage.getItem("pocket-flashcards-v1");setSets(saved?migrateLegacyExamples(safeSets(JSON.parse(saved))):seed)}catch{setSets(seed)}setReady(true)},[]);
  useEffect(()=>{if(ready)localStorage.setItem("pocket-flashcards-v1",JSON.stringify(sets))},[sets,ready]);
  const active=view.kind==="set"||view.kind==="study"?sets.find(s=>s.id===view.id):undefined;
  const update=(id:string,fn:(s:StudySet)=>StudySet)=>setSets(xs=>xs.map(s=>{if(s.id!==id)return s;const next=fn(s);const allFlash=next.terms.length>0&&next.terms.every(t=>t.flashcardExposures>=4);const allBank=next.terms.length>0&&next.terms.every(t=>t.wordBankRounds>=3);return {...next,wordBankUnlocked:next.wordBankUnlocked||allFlash,reviewUnlocked:next.reviewUnlocked||allBank,updatedAt:new Date().toISOString()}}));
  const toast=(s:string)=>{setNotice(s);setTimeout(()=>setNotice(""),2600)};
  const createSet=()=>{if(!draft.trim())return;const now=new Date().toISOString();const n:StudySet={id:uid(),title:draft.trim(),terms:[],lifetimePoints:0,wordBankUnlocked:false,reviewUnlocked:false,createdAt:now,updatedAt:now};setSets(x=>[n,...x]);setModal(null);setDraft("");setView({kind:"set",id:n.id})};
  const exportSet=(s:StudySet)=>{const blob=new Blob([JSON.stringify(s,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${s.title.toLowerCase().replace(/[^a-z0-9]+/g,"-")}.json`;a.click();URL.revokeObjectURL(a.href);toast("Backup downloaded")};
  const importFile=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;try{const incoming=safeSets(JSON.parse(await f.text()));setSets(x=>[...incoming,...x]);toast(`${incoming.length} set${incoming.length>1?"s":""} imported`)}catch(err){toast(err instanceof Error?err.message:"Could not import file")}e.target.value=""};
  const saveTerm=()=>{if(!active||!draft.trim()||!desc.trim())return;update(active.id,s=>({...s,terms:editId?s.terms.map(t=>t.id===editId?{...t,term:draft.trim(),description:desc.trim()}:t):[...s.terms,makeTerm(draft.trim(),desc.trim())]}));setModal(null);setDraft("");setDesc("");setEditId(null)};
  const resetReview=()=>{if(!active)return;update(active.id,s=>{const terms=s.terms.map(t=>{const completedReviews=Math.min(3,t.reviewRounds);return {...t,points:Math.max(0,t.points-completedReviews*10),attempts:Math.max(0,t.attempts-completedReviews),correct:Math.max(0,t.correct-completedReviews),streak:0,reviewRounds:0}});return {...s,terms,lifetimePoints:terms.reduce((sum,t)=>sum+t.points,0)}});setModal(null);toast("Term review progress reset")};
  const resetTerm=()=>{if(!active||!editId)return;update(active.id,s=>{const terms=s.terms.map(t=>t.id===editId?{...t,points:0,attempts:0,correct:0,streak:0,bestStreak:0,flashcardExposures:0,wordBankRounds:0,reviewRounds:0,retentionAttempts:0,retentionCorrect:0,lastTestedAt:undefined}:t);return {...s,terms,lifetimePoints:terms.reduce((sum,t)=>sum+t.points,0)}});setModal(null);setEditId(null);toast(`${draft} progress reset`)};
  if(!ready)return <main className="loading">{tr("Opening your study drawer…")}</main>;
  return <div className="app">
    <header><button className="brand" onClick={()=>setView({kind:"library"})} aria-label="Pocket Flashcards home"><span className="mark">P</span><span>{language==="mi"?<>Kāri Ako<br/>Pūkoro</>:<>Pocket<br/>Flashcards</>}</span></button><div className="header-tools"><div className="language-switch" role="group" aria-label="Interface language"><button className={language==="en"?"active":""} aria-pressed={language==="en"} onClick={()=>setLanguage("en")}>EN</button><button className={language==="mi"?"active":""} aria-pressed={language==="mi"} onClick={()=>setLanguage("mi")}>MI</button></div><div className="privacy">{tr("Review · Rinse · Repeat")}</div></div></header>
    {view.kind==="library"&&<Library sets={sets} open={id=>setView({kind:"set",id})} onTest={()=>setView({kind:"test"})} onNew={()=>{setDraft("");setModal("new")}} onImport={()=>fileRef.current?.click()} rename={s=>{setEditId(s.id);setDraft(s.title);setModal("rename")}} remove={s=>{setEditId(s.id);setDraft(s.title);setModal("delete")}} exportSet={exportSet}/>}
    {view.kind==="set"&&active&&<Overview set={active} back={()=>setView({kind:"library"})} study={stage=>setView({kind:"study",id:active.id,stage})} resetReview={()=>setModal("reset-review")} resetTerm={t=>{setEditId(t.id);setDraft(t.term);setModal("reset-term")}} add={()=>{setEditId(null);setDraft("");setDesc("");setModal("term")}} edit={t=>{setEditId(t.id);setDraft(t.term);setDesc(t.description);setModal("term")}} remove={t=>update(active.id,s=>({...s,terms:s.terms.filter(x=>x.id!==t.id)}))}/>}
    {view.kind==="study"&&active&&<Study set={active} stage={view.stage} exit={()=>setView({kind:"set",id:active.id})} update={fn=>update(active.id,fn)}/>}
    {view.kind==="test"&&<RecallTest sets={sets} exit={()=>setView({kind:"library"})} record={result=>setSets(current=>applyRetentionResult(current,result))}/>}
    <input ref={fileRef} hidden type="file" accept="application/json,.json" onChange={importFile}/>
    {modal&&<div className="backdrop" role="presentation"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button className="modal-close" onClick={()=>setModal(null)} aria-label="Close">×</button>
      {modal==="new"&&<><p className="eyebrow">{tr("New set")}</p><h2 id="modal-title">{tr("Name your study set")}</h2><label>{tr("Set title")}<input autoFocus value={draft} onChange={e=>setDraft(e.target.value)} placeholder={language==="mi"?"hei tauira, Toi hītori":"e.g. Art history"} onKeyDown={e=>e.key==="Enter"&&createSet()}/></label><button className="primary wide" onClick={createSet} disabled={!draft.trim()}>{tr("Create set")} <span>→</span></button></>}
      {modal==="rename"&&<><p className="eyebrow">{tr("Rename set")}</p><h2 id="modal-title">{tr("Choose a new name")}</h2><label>{tr("Set title")}<input autoFocus value={draft} onChange={e=>setDraft(e.target.value)}/></label><button className="primary wide" onClick={()=>{if(!editId||!draft.trim())return;update(editId,s=>({...s,title:draft.trim()}));setModal(null)}}>{tr("Save name")} <span>→</span></button></>}
      {modal==="delete"&&<><p className="eyebrow">{tr("Please take care")}</p><h2 id="modal-title">{language==="mi"?`Mukua “${draft}”?`:`Delete “${draft}”?`}</h2><p>{language==="mi"?"Ka mukua te huinga me tōna kauneke i tēnei pūtirotiro. Kaweakehia i te tuatahi mēnā ka hiahiatia ā muri ake.":"This removes the set and its progress from this browser. Export it first if you may need it later."}</p><div className="modal-actions"><button className="ghost" onClick={()=>setModal(null)}>{tr("Keep set")}</button><button className="danger" onClick={()=>{setSets(x=>x.filter(s=>s.id!==editId));setModal(null)}}>{tr("Delete set")}</button></div></>}
      {modal==="reset-review"&&<><p className="eyebrow">{tr("Reset progress")}</p><h2 id="modal-title">{language==="mi"?"Tautuhi anō i te Arotake Kupu?":"Reset Term Review?"}</h2><p>{language==="mi"?"Ka whakawāteatia te kauneke me ngā piro o te mahi tuatoru. Ka noho tonu ngā Kāri Ako me te Pēke Kupu.":"This clears all progress and score earned in the third exercise. Flash Cards and Word Bank will stay unchanged."}</p><div className="modal-actions"><button className="ghost" onClick={()=>setModal(null)}>{tr("Cancel")}</button><button className="danger" onClick={resetReview}>{tr("Reset review")}</button></div></>}
      {modal==="reset-term"&&<><p className="eyebrow">{tr("Reset term")}</p><h2 id="modal-title">{language==="mi"?`Tautuhi anō i “${draft}”?`:`Reset “${draft}”?`}</h2><p>{language==="mi"?"Ka whakawāteatia ngā mahi, ngā tatauranga, ngā raupapa me ngā piro katoa mō tēnei kupu. Ka noho tonu ērā atu kupu.":"This clears every exercise, statistic, streak, and score for this term. Other terms will stay unchanged."}</p><div className="modal-actions"><button className="ghost" onClick={()=>setModal(null)}>{tr("Cancel")}</button><button className="danger" onClick={resetTerm}>{tr("Reset term")}</button></div></>}
      {modal==="term"&&<><p className="eyebrow">{tr(editId?"Edit term":"New term")}</p><h2 id="modal-title">{tr(editId?"Update this term":"Add a term")}</h2><label>{tr("Term")}<input autoFocus value={draft} onChange={e=>setDraft(e.target.value)} placeholder={language==="mi"?"Te kupu, te pātai rānei":"The word or prompt"}/></label><label>{tr("Description")}<textarea value={desc} onChange={e=>setDesc(e.target.value)} placeholder={language==="mi"?"Te whakautu, te whakamārama rānei":"The answer or explanation"}/></label><button className="primary wide" onClick={saveTerm} disabled={!draft.trim()||!desc.trim()}>{tr(editId?"Save changes":"Add a term")} <span>→</span></button></>}
    </section></div>}
    {notice&&<div className="toast" role="status">✓ {notice}</div>}
  </div>
}

function Library({sets,open,onTest,onNew,onImport,rename,remove,exportSet}:{sets:StudySet[];open:(id:string)=>void;onTest:()=>void;onNew:()=>void;onImport:()=>void;rename:(s:StudySet)=>void;remove:(s:StudySet)=>void;exportSet:(s:StudySet)=>void}){
  const {tr,language}=useLanguage();
  const recallable=eligibleRecallTerms(sets).length;
  return <main><section className="hero"><div><p className="eyebrow">{tr("Pocket Flashcards")}</p><h1>{language==="mi"?<>Arotake. Ako anō.<br/><em>Tāruarua.</em></>:<>Review. Rinse.<br/><em>Repeat.</em></>}</h1><p className="lede">{tr("Create a set, practise the terms, and track your progress.")}</p></div><div className="hero-actions"><button className="primary" onClick={onNew}><b>＋</b> {tr("New study set")}</button><button className="ghost" onClick={onImport}>⇩ {tr("Import JSON")}</button></div></section>
  <section className="recall-invite"><div><p className="eyebrow">{tr("Across all your topics")}</p><h2>{tr("How much has stuck?")}</h2><p>{tr("Type five terms from memory. Recall tests measure retention without changing your learning progress.")}</p></div><button className="primary" onClick={onTest} disabled={!recallable}>{tr("Start recall test")} <span>→</span></button><small>{recallable?(language==="mi"?`Ka kōwhiria ${Math.min(5,recallable)} o ngā kupu āhei ${recallable}`:`${Math.min(5,recallable)} of ${recallable} eligible terms will be chosen`):tr("Complete the flashcard stage for a term to make it eligible")}</small></section>
  <section className="library"><div className="section-title"><h2>{tr("Your study sets")}</h2><span>{sets.length} {tr(sets.length===1?"collection":"collections")}</span></div>
  {sets.length===0?<div className="empty"><span>✦</span><h3>{tr("Your library is waiting.")}</h3><p>{tr("Create a small set and begin with one card at a time.")}</p><button className="primary" onClick={onNew}>{tr("Create your first set")}</button></div>:<div className="set-grid">{sets.map((s,i)=><article className={`set-card tone-${i%3}`} key={s.id}><div className="set-top"><span className="avatar">{s.title.charAt(0).toUpperCase()}</span><div className="menu"><button aria-label={`Rename ${s.title}`} onClick={()=>rename(s)}>✎</button><button aria-label={`Export ${s.title}`} onClick={()=>exportSet(s)}>↓</button><button aria-label={`Delete ${s.title}`} onClick={()=>remove(s)}>×</button></div></div><button className="card-open" onClick={()=>open(s.id)}><h3>{s.title}</h3><p>{s.terms.length} {tr("terms")}</p><div className="progress-row"><div className="progress"><i style={{width:`${s.terms.length?completed(s)/s.terms.length*100:0}%`}}/></div><span>{completed(s)} {tr("complete")}</span></div><span className="open-label">{tr("Open set")} <b>↗</b></span></button></article>)}</div>}
  <p className="source-credit">{tr("Example place-name meanings from NZ History’s Māori Language Week resource.")} <a href="https://nzhistory.govt.nz/culture/maori-language-week/1000-maori-place-names" target="_blank" rel="noreferrer">NZ History ↗</a></p></section><Footer/></main>
}

function Overview({set,back,study,resetReview,resetTerm,add,edit,remove}:{set:StudySet;back:()=>void;study:(s:"flash"|"bank"|"review")=>void;resetReview:()=>void;resetTerm:(t:Term)=>void;add:()=>void;edit:(t:Term)=>void;remove:(t:Term)=>void}){
 const {tr,language}=useLanguage();
 const allFlash=set.terms.length>0&&set.terms.every(t=>t.flashcardExposures>=4),allBank=set.terms.length>0&&set.terms.every(t=>t.wordBankRounds>=3),wordBankOpen=set.wordBankUnlocked||allFlash,reviewOpen=set.reviewUnlocked||allBank,next=stageFor(set);
 const finished=set.terms.filter(t=>completion(t)===100);const [finishedIndex,setFinishedIndex]=useState(0);const finishedTerm=finished[finishedIndex%Math.max(1,finished.length)];
 return <main><button className="back" onClick={back}>← {tr("Back to library")}</button><section className="set-hero"><div><p className="eyebrow">{tr("Study set")} · {set.terms.length} {tr("terms")}</p><h1>{set.title}</h1><p className="lede">{tr("Review your terms and keep progressing.")}</p></div><div className="points"><small>{tr("Score")}</small><strong>{set.lifetimePoints}</strong><span>5 {tr("per exposure")} · 10 {tr("per correct")}</span></div></section>
 <section className="path"><div className="section-title"><div><p className="eyebrow">{tr("Study progress")}</p><h2>{tr("Three stages")}</h2></div><div className="path-actions">{set.terms.some(t=>t.reviewRounds>0)&&<button className="ghost" onClick={resetReview}>{tr("Reset term review")}</button>}<button className="primary" disabled={!set.terms.length} onClick={()=>study(next)}>{tr("Continue studying")} <span>→</span></button></div></div><div className="stage-grid">
  <Stage n="01" title={tr("Flash cards")} copy={tr("Four alternating exposures per term.")} progress={set.terms.reduce((a,t)=>a+Math.min(t.flashcardExposures,4),0)} total={set.terms.length*4} open={!!set.terms.length} onClick={()=>study("flash")}/>
  <Stage n="02" title={tr("Word bank")} copy={tr("Choose the missing answer. Three correct rounds.")} progress={set.terms.reduce((a,t)=>a+Math.min(t.wordBankRounds,3),0)} total={set.terms.length*3} open={wordBankOpen} onClick={()=>study("bank")}/>
  <Stage n="03" title={tr("Term review")} copy={tr("15% hidden, then 50%, then full recall.")} progress={set.terms.reduce((a,t)=>a+Math.min(t.reviewRounds,3),0)} total={set.terms.length*3} open={reviewOpen} onClick={()=>study("review")}/>
 </div></section>
 {finishedTerm&&<section className="mastered"><div className="section-title"><div><p className="eyebrow">{tr("Completed terms")}</p><h2>{tr("Flip through your terms")}</h2></div><span>{finishedIndex%finished.length+1} {language==="mi"?"o":"of"} {finished.length}</span></div><article className="mastered-card"><button aria-label="Previous completed term" onClick={()=>setFinishedIndex(index=>(index-1+finished.length)%finished.length)}>←</button><div><p>{tr("TERM")}</p><h3>{finishedTerm.term}</h3><i/><p>{tr("DESCRIPTION")}</p><strong>{finishedTerm.description}</strong></div><button aria-label="Next completed term" onClick={()=>setFinishedIndex(index=>(index+1)%finished.length)}>→</button></article></section>}
 <section className="terms"><div className="section-title"><div><p className="eyebrow">{tr("Inside this set")}</p><h2>{tr("Terms & progress")}</h2></div><button className="ghost" onClick={add}>＋ {tr("Add a term")}</button></div>
 {set.terms.length===0?<div className="empty compact"><span>✦</span><h3>{tr("Make your first card.")}</h3><p>{tr("Add a term and description to begin studying.")}</p></div>:<div className="term-list">{set.terms.map(t=><article className="term-row" key={t.id}><div className="term-copy"><h3>{t.term}</h3><p>{t.description}</p></div><div className="stat"><strong>{t.points}</strong><span>{tr("score")}</span></div><div className="stat"><strong>{t.correct}/{t.attempts}</strong><span>{tr("correct")}</span></div><div className="stat"><strong>{t.retentionAttempts?`${retentionPercentage(t)}%`:"—"}</strong><span>{tr("retention")}</span></div><div className="stat"><strong>{t.bestStreak}</strong><span>{tr("best streak")}</span></div><div className="complete"><strong>{completion(t)}%</strong><div className="progress"><i style={{width:`${completion(t)}%`}}/></div></div><div className="row-actions"><button aria-label={`Reset progress for ${t.term}`} onClick={()=>resetTerm(t)}>↺</button><button aria-label={`Edit ${t.term}`} onClick={()=>edit(t)}>✎</button><button aria-label={`Delete ${t.term}`} onClick={()=>remove(t)}>×</button></div></article>)}</div>}
 </section><Footer/></main>
}

function Stage({n,title,copy,progress,total,open,onClick}:{n:string;title:string;copy:string;progress:number;total:number;open:boolean;onClick:()=>void}){const {tr,language}=useLanguage();const pct=total?Math.round(progress/total*100):0;return <button className={`stage ${open?"":"locked"}`} disabled={!open} onClick={onClick}><span className="stage-num">{n}</span><span className="stage-state">{open?tr(pct===100?"Completed":"Ready to practise"):`⌑ ${tr("Locked")}`}</span><h3>{title}</h3><p>{copy}</p><div className="progress"><i style={{width:`${pct}%`}}/></div><small>{open?(language==="mi"?`${progress} o ${total} kua oti`:`${progress} of ${total} complete`):tr("Complete the stage before this one")}</small></button>}

function Study({set,stage,exit,update}:{set:StudySet;stage:"flash"|"bank"|"review";exit:()=>void;update:(f:(s:StudySet)=>StudySet)=>void}){
 const {tr,language}=useLanguage();
 const needsStage=(t:Term)=>stage==="flash"?t.flashcardExposures<4:stage==="bank"?t.flashcardExposures>=4&&t.wordBankRounds<3:t.wordBankRounds>=3&&t.reviewRounds<3;
 const eligible=set.terms.filter(needsStage);const [index,setIndex]=useState(0);const [revealed,setRevealed]=useState(false);const [answer,setAnswer]=useState("");const [selectedLetters,setSelectedLetters]=useState<number[]>([]);const [feedback,setFeedback]=useState<null|boolean>(null);const [current,setCurrent]=useState<Term|undefined>(()=>eligible[0]);
 const flip=(current?.flashcardExposures??0)%2===1;const title=stage==="flash"?tr("Flash cards"):stage==="bank"?tr("Word bank"):tr("Term review");
 const choices=useMemo(()=>current?[current.term,...set.terms.filter(t=>t.id!==current.id).map(t=>t.term)].slice(0,4).sort((a,b)=>a.localeCompare(b)):[],[current,set.terms]);
 const cloze=useMemo(()=>current&&current.reviewRounds<2?makeCloze(current.term,current.reviewRounds===0?.15:.5,`${current.id}-${current.reviewRounds}`):null,[current]);
 const letterBank=useMemo(()=>{
   if(!cloze||!current)return [];
   const round=current.reviewRounds;
   const fraction=round===0?.15:.5;
   const roundLetters=set.terms.map(term=>makeCloze(term.term,fraction,`${term.id}-${round}`).missing).join("");
   return makeLetterBank(roundLetters,`${set.id}-${round}-bank`);
 },[cloze,current,set.id,set.terms]);
 const reviewExpected=cloze?cloze.missing:current?.term||"";
 const reviewIsCorrect=()=>cloze?normalizeAnswer(answer).replace(/\s/g,"")===normalizeAnswer(reviewExpected).replace(/\s/g,""):normalizeAnswer(answer)===normalizeAnswer(reviewExpected);
 const score=(correct:boolean)=>{if(!current)return;update(s=>({...s,lifetimePoints:s.lifetimePoints+(correct?10:0),terms:s.terms.map(t=>t.id!==current.id?t:{...t,points:t.points+(correct?10:0),attempts:t.attempts+1,correct:t.correct+(correct?1:0),streak:correct?t.streak+1:0,bestStreak:correct?Math.max(t.bestStreak,t.streak+1):t.bestStreak,...(correct?(stage==="bank"?{wordBankRounds:Math.min(3,t.wordBankRounds+1)}:{reviewRounds:Math.min(3,t.reviewRounds+1)}):{})})}));setFeedback(correct)};
 const next=()=>{if(!current)return;const projectedTerms=stage==="flash"?set.terms.map(t=>t.id===current.id?{...t,flashcardExposures:Math.min(4,t.flashcardExposures+1),points:t.points+5}:t):set.terms;if(stage==="flash")update(s=>({...s,lifetimePoints:s.lifetimePoints+5,terms:projectedTerms}));const currentPosition=projectedTerms.findIndex(t=>t.id===current.id);const ordered=[...projectedTerms.slice(currentPosition+1),...projectedTerms.slice(0,currentPosition+1)];const nextTerm=ordered.find(needsStage);setCurrent(nextTerm?{...nextTerm}:undefined);setRevealed(false);setFeedback(null);setAnswer("");setSelectedLetters([]);setIndex(i=>i+1)};
 if(!current)return <main className="study-shell"><button className="back" onClick={exit}>← {language==="mi"?"Tirohanga huinga":"Set overview"}</button><div className="study-complete"><span>✦</span><p className="eyebrow">{tr("Stage complete")}</p><h1>{tr("Stage complete")}.</h1><p>{tr("Your next study stage is ready.")}</p><button className="primary" onClick={exit}>{tr("Return to your set")} →</button></div></main>;
 return <main className="study-shell"><div className="study-nav"><button className="back" onClick={exit}>← {tr("Leave practice")}</button><div><span>{title}</span><div className="progress"><i style={{width:`${((index+1)/(eligible.length+index))*100}%`}}/></div></div><strong>✦ {set.lifetimePoints}</strong></div><section className="study-head"><p className="eyebrow">{stage==="flash"?`${tr("Exposure")} ${current.flashcardExposures+1} ${language==="mi"?"o":"of"} 4`:stage==="bank"?`${tr("Correct round")} ${current.wordBankRounds+1} ${language==="mi"?"o":"of"} 3`:`${tr("Review")} ${current.reviewRounds+1} ${language==="mi"?"o":"of"} 3`}</p><h1>{tr(stage==="flash"?"Review the card.":stage==="bank"?"Choose the answer.":"Type the answer.")}</h1></section>
 {stage==="flash"?<div className={`flashcard ${revealed?"revealed":""}`}><p>{tr(flip?"DESCRIPTION":"TERM")}</p><h2>{flip?current.description:current.term}</h2><div className="card-divider"/><p>{tr(flip?"TERM":"DESCRIPTION")}</p>{revealed?<h3>{flip?current.term:current.description}</h3>:<button className="reveal" onClick={()=>setRevealed(true)}>{tr(flip?"Reveal the term":"Reveal the description")} <span>↻</span></button>}</div>:stage==="bank"?<div className="quiz"><div className="prompt"><p>{tr("Which term matches this description?")}</p><h2>{current.description}</h2></div><div className="choices">{choices.map(c=><button key={c} disabled={feedback!==null} className={feedback!==null?(c===current.term?"correct":c===answer?"wrong":""):""} onClick={()=>{setAnswer(c);score(c===current.term)}}>{c}<span>{feedback!==null&&c===current.term?"✓":"○"}</span></button>)}</div></div>:<div className="quiz review"><div className="prompt"><p>{cloze?(language==="mi"?`Kua huna te ${current.reviewRounds===0?"15":"50"}% o te kupu`:`${current.reviewRounds===0?"15":"50"}% of the term is hidden`):tr("Type the complete term")}</p>{cloze&&<h2 className="cloze-term" aria-label="Term with missing letters">{cloze.masked}</h2>}<span className="review-description">{current.description}</span></div>{feedback!==null?<div className="resolved-term"><span>{tr("Complete term")}</span><strong>{current.term}</strong></div>:cloze?<div className="letter-picker"><p>{tr("Choose from all missing letters in this round")}</p><div className="letter-answer" aria-label={`Selected letters: ${answer||"none"}`}>{Array.from(cloze.missing).map((_,position)=><span key={position}>{Array.from(answer)[position]||""}</span>)}</div><div className="letter-bank" aria-label="Missing letter bank">{letterBank.map(({letter,index})=><button key={index} disabled={selectedLetters.includes(index)||selectedLetters.length>=Array.from(cloze.missing).length} onClick={()=>{setSelectedLetters(items=>[...items,index]);setAnswer(value=>value+letter)}} aria-label={`Add letter ${letter}`}>{letter}</button>)}</div><button className="undo-letter" disabled={!selectedLetters.length} onClick={()=>{setSelectedLetters(items=>items.slice(0,-1));setAnswer(value=>Array.from(value).slice(0,-1).join(""))}}>← {tr("Undo last letter")}</button></div>:<label className="answer">{tr("Complete term")}<input autoFocus value={answer} onChange={e=>setAnswer(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&answer.trim())score(reviewIsCorrect())}} placeholder={language==="mi"?"Patohia te kupu katoa…":"Type the whole term…"}/></label>}{feedback===null?<button className="primary" disabled={!answer.trim()||Boolean(cloze&&Array.from(answer).length<Array.from(cloze.missing).length)} onClick={()=>score(reviewIsCorrect())}>{tr("Check answer")} →</button>:<p className={`feedback ${feedback?"good":"bad"}`}>{tr(feedback?"Correct.":"Incorrect.")}</p>}</div>}
 <div className="study-footer"><p>{feedback===true?(language==="mi"?"+10 ki ō piro.":"+10 to your score."):feedback===false?(language==="mi"?"Kāore he piro i tāpirihia.":"No score added."):stage==="flash"?(language==="mi"?"Whakaotia tēnei whakakitenga kia 5 ngā piro tāpiri.":"Complete this exposure to add 5 to your score."):(language==="mi"?"Kōwhiria he whakautu kia haere tonu.":"Select an answer to continue.")}</p><button className="primary" disabled={stage==="flash"?!revealed:feedback===null} onClick={next}>{tr(stage==="flash"?"Next exposure":"Next term")} <span>→</span></button></div></main>
}

type RecallAnswer = RecallTerm & {answer:string;correct:boolean};

function RecallTest({sets,exit,record}:{sets:StudySet[];exit:()=>void;record:(result:RetentionResult)=>void}){
 const {tr,language}=useLanguage();
 const [questions,setQuestions]=useState<RecallTerm[]>(()=>selectRecallTerms(sets,5));const [index,setIndex]=useState(0);const [answer,setAnswer]=useState("");const [feedback,setFeedback]=useState<boolean|null>(null);const [answers,setAnswers]=useState<RecallAnswer[]>([]);const [finished,setFinished]=useState(false);const current=questions[index];
 const submit=()=>{if(!current||!answer.trim()||feedback!==null)return;const correct=normalizeAnswer(answer)===normalizeAnswer(current.term);setAnswers(items=>[...items,{...current,answer:answer.trim(),correct}]);record({setId:current.setId,termId:current.termId,correct});setFeedback(correct)};
 const next=()=>{if(index>=questions.length-1){setFinished(true);return}setIndex(value=>value+1);setAnswer("");setFeedback(null)};
 const restart=()=>{setQuestions(selectRecallTerms(sets,5));setIndex(0);setAnswer("");setFeedback(null);setAnswers([]);setFinished(false)};
 if(!questions.length)return <main className="recall-shell"><section className="recall-card recall-empty"><p className="eyebrow">{tr("Recall test")}</p><h1>{tr("No terms are ready yet")}</h1><p>{tr("Complete the flashcard stage for at least one term, then come back to test what you remember.")}</p><button className="primary" onClick={exit}>{tr("Return to library")}</button></section></main>;
 if(finished){const correct=answers.filter(item=>item.correct).length;return <main className="recall-shell"><section className="recall-results"><p className="eyebrow">{tr("Recall test complete")}</p><h1>{correct} {language==="mi"?"o":"of"} {answers.length} {tr("correct")}</h1><p>{tr("Your retention results are tracked separately and do not change study progress or score.")}</p><div className="recall-result-list">{answers.map(item=><article className={`recall-result ${item.correct?"is-correct":"is-incorrect"}`} key={`${item.setId}-${item.termId}`}><div><span>{item.setTitle}</span><strong>{item.term}</strong><p>{item.description}</p></div><div className="recall-result-answer"><span>{tr("Your answer")}</span><strong>{item.answer}</strong><em>{tr(item.correct?"Correct":"Not quite")}</em></div></article>)}</div><div className="recall-actions"><button className="primary" onClick={restart}>{tr("Test another five")}</button><button className="ghost" onClick={exit}>{tr("Return to library")}</button></div></section></main>}
 return <main className="recall-shell"><nav className="recall-nav"><button className="text-button" onClick={exit}>← {tr("Leave test")}</button><span>{tr("Recall test")}</span><span>{index+1} {language==="mi"?"o":"of"} {questions.length}</span></nav><section className="recall-card"><p className="eyebrow">{current.setTitle}</p><h1>{tr("What term matches this description?")}</h1><blockquote>{current.description}</blockquote><label className="recall-answer"><span>{tr("Type the complete term")}</span><input autoFocus value={answer} disabled={feedback!==null} onChange={event=>setAnswer(event.target.value)} onKeyDown={event=>{if(event.key==="Enter")submit()}} /></label>{feedback!==null&&<div className={`recall-feedback ${feedback?"is-correct":"is-incorrect"}`} role="status"><strong>{tr(feedback?"Correct.":"Not quite.")}</strong><span>{tr("The term is")} {current.term}.</span></div>}<div className="recall-actions">{feedback===null?<button className="primary" disabled={!answer.trim()} onClick={submit}>{tr("Check answer")}</button>:<button className="primary" onClick={next}>{tr(index===questions.length-1?"See results":"Next question")}</button>}</div></section></main>
}

function Footer(){const {tr}=useLanguage();return <footer><span>P</span><p><strong>{tr("Pocket Flashcards")}</strong><br/>{tr("Review. Rinse. Repeat.")}</p><small>{tr("Study one set at a time.")}</small></footer>}
